#!/usr/bin/env node
import { createHash } from "node:crypto";
import { access, mkdir, readFile, rename, writeFile } from "node:fs/promises";
import path from "node:path";
import { performance } from "node:perf_hooks";
import { pathToFileURL } from "node:url";
import { chromium } from "../.e2e/node_modules/playwright/index.mjs";

const defaults=["https://outstanding.kr/chazm20260811","https://outstanding.kr/accelerators20260818","https://outstanding.kr/newdb20260812"];
const urls=process.argv.slice(2).length?process.argv.slice(2):defaults;
const root=path.resolve(import.meta.dirname,".."), dataRoot=path.join(root,".localdata/outstanding"), exportRoot=path.join(dataRoot,"exports"), cacheRoot=path.join(dataRoot,"image-cache"), blobRoot=path.join(cacheRoot,"blobs"), indexPath=path.join(cacheRoot,"index.json");
const began=performance.now();
await Promise.all([mkdir(exportRoot,{recursive:true}),mkdir(blobRoot,{recursive:true})]);
const esc=(s="")=>s.replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
const exists=(f)=>access(f).then(()=>true,()=>false);
const ext=(type,url)=>({"image/jpeg":".jpg","image/png":".png","image/gif":".gif","image/webp":".webp","image/svg+xml":".svg","image/avif":".avif"}[type.split(";")[0].toLowerCase()]||path.extname(new URL(url).pathname)||".img");
const mapLimit=async(items,limit,fn)=>{const out=new Array(items.length);let next=0;await Promise.all(Array.from({length:Math.min(limit,items.length)},async()=>{while(next<items.length){const i=next++;out[i]=await fn(items[i],i)}}));return out};
let cache={version:1,urls:{}};try{cache=JSON.parse(await readFile(indexPath,"utf8"))}catch{}

// Outstanding serves truncated content to true headless Chrome. Run normal Chrome off-screen: no visible window.
const context=await chromium.launchPersistentContext(path.join(root,".outstanding-profile"),{channel:"chrome",headless:false,viewport:null,args:["--window-position=-10000,-10000","--window-size=1440,1000"]});
await context.route(/\.(?:woff2?|ttf|otf|mp4|webm)(?:\?|$)/i,r=>r.abort());
const collect=async(url)=>{const page=await context.newPage();await page.route(/\.(?:jpe?g|png|gif|webp|svg|avif)(?:\?|$)/i,r=>r.abort());await page.goto(url,{waitUntil:"domcontentloaded"});const selector='[role="article"][aria-label="article-content"]';await page.waitForSelector(selector,{timeout:30000});await page.waitForFunction(sel=>{const t=document.querySelector(sel)?.innerText||"";return t.length>1000&&!t.includes("전체 콘텐츠를 보려면 로그인")},selector,{timeout:45000});await page.waitForTimeout(400);const body=page.locator(selector).first(),title=(await page.locator("h1").first().innerText().catch(()=>page.title())).trim(),published=await page.locator('meta[property="article:published_time"]').getAttribute("content").catch(()=>"");const imageUrls=await body.locator("img").evaluateAll(images=>{const all=[];for(const img of images){let chosen=img.getAttribute("data-src")||img.getAttribute("src");if(!chosen||chosen.startsWith("data:")){const set=img.getAttribute("data-srcset")||img.getAttribute("srcset");if(set)chosen=set.split(",").map(x=>x.trim().split(/\s+/)[0]).filter(Boolean).at(-1)}if(chosen)try{all.push(new URL(chosen,location.href).href)}catch{}}return [...new Set(all)]});return{url,page,body,title,published,imageUrls,slug:new URL(url).pathname.split("/").filter(Boolean).pop()}};

console.log(`기사 ${urls.length}개 병렬 로딩...`);
const records=await Promise.all(urls.map(collect));
const unique=[...new Set(records.flatMap(r=>r.imageUrls))], urlToBlob=new Map();let hits=0,downloads=0,duplicates=0;
console.log(`이미지 참조 ${records.reduce((n,r)=>n+r.imageUrls.length,0)}개 → 고유 URL ${unique.length}개, 동시 처리 8개`);
await mapLimit(unique,8,async url=>{const hit=cache.urls[url];if(hit&&await exists(path.join(cacheRoot,hit.blob))){hits++;urlToBlob.set(url,hit.blob);return}try{const response=await context.request.get(url,{headers:{referer:"https://outstanding.kr/"},timeout:30000}),type=response.headers()["content-type"]||"";if(!response.ok()||!type.startsWith("image/"))return;const bytes=await response.body(),hash=createHash("sha256").update(bytes).digest("hex"),blob=`blobs/${hash}${ext(type,url)}`,target=path.join(cacheRoot,blob);if(await exists(target))duplicates++;else await writeFile(target,bytes,{mode:0o600});cache.urls[url]={blob,contentType:type,bytes:bytes.length};urlToBlob.set(url,blob);downloads++}catch(e){console.error(`이미지 실패: ${url} (${e.message})`)}});
await writeFile(`${indexPath}.tmp`,JSON.stringify(cache,null,2),{mode:0o600});await rename(`${indexPath}.tmp`,indexPath);

const results=await Promise.all(records.map(async r=>{const replacements=r.imageUrls.flatMap(url=>urlToBlob.has(url)?[[url,`../../image-cache/${urlToBlob.get(url)}`]]:[]);const articleHtml=await r.body.evaluate((element,entries)=>{const clone=element.cloneNode(true),map=new Map(entries);clone.querySelectorAll("script,style,iframe,button,nav,form").forEach(n=>n.remove());clone.querySelectorAll("img").forEach(img=>{const candidates=[img.getAttribute("src"),img.getAttribute("data-src")].filter(Boolean).map(x=>new URL(x,location.href).href),match=candidates.find(x=>map.has(x));if(!match){img.remove();return}img.setAttribute("src",map.get(match));["srcset","data-src","data-srcset","loading"].forEach(a=>img.removeAttribute(a))});clone.querySelectorAll("a[href]").forEach(a=>a.href=new URL(a.getAttribute("href"),location.href).href);return clone.innerHTML},replacements);const dir=path.join(exportRoot,r.slug);await mkdir(dir,{recursive:true});const htmlPath=path.join(dir,`${r.slug}.html`),pdfPath=path.join(dir,`${r.slug}.pdf`),html=`<!doctype html><html lang="ko"><head><meta charset="utf-8"><title>${esc(r.title)}</title><style>@page{size:A4;margin:17mm 15mm 19mm}*{box-sizing:border-box}body{color:#222;font:16px/1.78 -apple-system,BlinkMacSystemFont,"Apple SD Gothic Neo",sans-serif}article{max-width:760px;margin:40px auto}h1{font-size:30px;line-height:1.35}.meta{color:#777;font-size:13px;border-bottom:1px solid #ddd;padding-bottom:18px;margin-bottom:28px}h2,h3{break-after:avoid}p{margin:0 0 1em}img{display:block;max-width:100%;height:auto;margin:22px auto;break-inside:avoid}a{color:inherit;text-decoration:none}@media print{article{max-width:none;margin:0}}</style></head><body><article><h1>${esc(r.title)}</h1><div class="meta">${esc(r.published||"")} · 원문: ${esc(r.url)}</div>${articleHtml}</article></body></html>`;await writeFile(htmlPath,html,{mode:0o600});await r.page.close();return{slug:r.slug,title:r.title,htmlPath,pdfPath,images:replacements.length}}));
await context.close();
const pdfBrowser=await chromium.launch({headless:true});await mapLimit(results,2,async r=>{const page=await pdfBrowser.newPage();await page.goto(pathToFileURL(r.htmlPath).href,{waitUntil:"load"});await page.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.images].map(i=>i.decode().catch(()=>{})))});await page.pdf({path:r.pdfPath,format:"A4",printBackground:true,displayHeaderFooter:true,headerTemplate:"<span></span>",footerTemplate:'<div style="font-size:9px;color:#888;width:100%;text-align:center"><span class="pageNumber"></span> / <span class="totalPages"></span></div>',margin:{top:"17mm",right:"15mm",bottom:"19mm",left:"15mm"}});await page.close()});await pdfBrowser.close();
console.log(`완료 ${((performance.now()-began)/1000).toFixed(1)}초 · 캐시 적중 ${hits} · 다운로드 ${downloads} · 내용 중복 ${duplicates}`);for(const r of results)console.log(`${r.slug}: 이미지 ${r.images}개\n  HTML ${r.htmlPath}\n  PDF  ${r.pdfPath}`);
